#!/bin/bash

echo What is the name of your project?
read projectname

mkdir -p $HOME/Desktop/$projectname/{img,js,css}

touch $HOME/Desktop/$projectname/{css/styles.css,js/$projectname.js,js/$projectname-interface.js,index.html,README.md,.gitignore}
cd $HOME/Desktop/$projectname

git init
npm init
npm install bower -g
bower init
bower install bootstrap
bower install jquery
npm install gulp --save-dev
npm install gulp -g
npm install browserify --save-dev
npm install uglify --save-dev
npm install gulp-uglify --save-dev
npm install gulp-util --save-dev
npm install del --save-dev
npm install jshint --save-dev
npm install gulp-jshint --save-dev
npm install gulp-babel --save-dev
npm install gulp-concat --save-dev
npm install vinyl-source-stream --save-dev
npm install babel-preset-es2015 --save-dev
npm install browser-sync --save-dev
npm install bower-files --save-dev

cat >>index.html <<'EOM'
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="build/js/app.js"></script>
    <link href="css/styles.css" rel="stylesheet" type="text/css">
    <title></title>
  </head>
  <body>
  </body>
</html>
EOM

cat >>gulpfile.js <<'EOM'
var gulp = require('gulp'),
  browserify = require('browserify'),
  source = require('vinyl-source-stream'),
  concat = require('gulp-concat'),
  uglify = require('gulp-uglify'),
  utilities = require('gulp-util'),
  del = require('del'),
  jshint = require('gulp-jshint'),
  babel = require("gulp-babel"),
  browserSync = require('browser-sync').create(),
  lib = require('bower-files')({
  "overrides":{
    "bootstrap" : {
      "main": [
        "less/bootstrap.less",
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
});
gulp.task('serve', function() {
  browserSync.init({
  server: {
    baseDir: "./",
      index: "index.html"
    }
  });
  gulp.watch(['./js/*.js'], ['jsBuild']);
  gulp.watch(['bower.json'], ['bowerBuild']);
  gulp.watch(['*.html'], ['htmlBuild']);
});
gulp.task('htmlBuild', function() {
  browserSync.reload();
});
gulp.task('bowerBuild', ['bower'], function(){
  browserSync.reload();
});
gulp.task("clean", function(){
  return del(['build', 'tmp']);
});
gulp.task('jsBuild', ['jsBrowserify', 'jshint'], function(){
  browserSync.reload();
});
gulp.task('bowerCSS', function () {
  return gulp.src(lib.ext('css').files)
    .pipe(concat('vendor.css'))
    .pipe(gulp.dest('./build/css'));
});
gulp.task('bowerJS', function () {
  return gulp.src(lib.ext('js').files)
    .pipe(concat('vendor.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest('./build/js'));
});
gulp.task('bower', ['bowerJS', 'bowerCSS']);
gulp.task("build", ['clean'], function(){
  var buildProduction = utilities.env.production;
  if (buildProduction) {
    gulp.start('minifyScripts');
  } else {
    gulp.start('jsBrowserify');
  }
  gulp.start('bower');
});
gulp.task('jsBrowserify', ['concatInterface'], function() {
  return browserify({ entries: ['./tmp/allConcat.js'] })
    .bundle()
    .pipe(source('app.js'))
    .pipe(gulp.dest('./build/js'));
});
gulp.task('concatInterface', function() {
  return gulp.src(['./js/*-interface.js'])
    .pipe(concat('allConcat.js'))
    .pipe(gulp.dest('./tmp'));
});
gulp.task("minifyScripts", ["jsBrowserify"], function(){
  return gulp.src("./build/js/app.js")
    .pipe(babel({
      presets: ['es2015']
    }))
    .pipe(uglify())
    .pipe(gulp.dest("./build/js"));
});
gulp.task('jshint', function(){
  return gulp.src(['js/*.js'])
    .pipe(jshint())
    .pipe(jshint.reporter('default'));
});
EOM

cat >>.gitignore <<'EOM'
node_modules/
.DS_Store
EOM

cat >>README.md <<'EOM'
# README title
This is a brief description of what the software does.
### Setup/Installation Requirements
* list item 1
* list item 2
* list item 3
### Known Bugs
List known bugs or issues here
### Technologies Used
* Tech 1
* Tech 2
* Tech 3
### By Authors
### Support and contact details
_contact info here_
### License
_MIT_
Copyright (c) _year_ **Author or Organization**
EOM

atom .
